#!/usr/bin/env python
# vim: et:ts=4:sw=4

import os
import optparse
from pync import Filetree

def main():
    parser = optparse.OptionParser(usage="usage: %prog [options] [repository] target_dir")
    parser.add_option(
        "-m", "--max-size", help="how much space to use up as a maximum (kilobytes)",
        dest="size", action="store", type="int"
    )
    options, args = parser.parse_args()

    if not args or len(args) not in (1,2):
      parser.error("incorrect number of arguments")

    target = Filetree(args[-1])
    if len(args) > 1:
        repo = Filetree(args[0])
    else:
        repo = Filetree(".")

    repo.compare_to(target)
    repo.trace(stop=(Filetree.S_ALL, Filetree.S_NONE))

main()
