#!/usr/bin/env python
# vim: et:ts=4:sw=4

import os
import argparse
import optparse
from cmd import Cmd
from pync import Filetree
from pync.prompt import Prompt

parser = argparse.ArgumentParser()
parser.add_argument(
    "-m", "--max-size", help="how much space to use up as a maximum (kilobytes)",
    type=int
)
parser.add_argument(
    "-d", "--debug", help="start in debug mode",
    action="store_true"
)
parser.add_argument(
    "repo", help="the repository to sync from",
    nargs="?", default="."
)
parser.add_argument(
    "target", help="the directory to sync to"
)
args = parser.parse_args()

import time
target = Filetree(args.target)
repo = Filetree(args.repo)

if args.debug:
    import pdb
    pdb.set_trace()
else:
    Prompt(repo, target).cmdloop()
